### PR TITLE
Small fixes and optimizations

### PR DESCRIPTION
**Pull request by kkevinm**
- asm/bounce.asm: removed redundant SEC (carry is already set there)
- asm/cluster.asm: removed redundant SEC, replaced constant #$09 with !ClusterOffset define and fixed init loop not resetting $1E02-$1E03 (since it doesn't loop back when X = 0)
- asm/extended.asm: removed redundant SEC
- asm/main.asm: removed redundant SEC and replaced shooter addresses with defines
- asm/minorextended.asm: removed redundant SEC
- asm/score.asm: removed redundant SEC
- asm/smoke.asm: removed redundant SEC
- asm/spinningcoin.asm: removed redundant SEC
- routines/Bounce/GenericDraw.asm: optimized OAM copy with 16 bit mode
- routines/Bounce/GetDrawInfo.asm: added |!dp to operations with absolute DP addresses for SA-1 compatibility
- routines/CheckForContactAlternate.asm: removed redundant SEC
- routines/ClusterGetDrawInfo.asm: fixed documentation
- routines/MinorExtended/GetDrawInfo.asm: replaced "clc : adc #$10" with "adc #$0F" (carry is set beforehand, so ADC adds 1)
- routines/Score/GenericDraw.asm: replaced "clc : adc #$08" with "adc #$07" (carry is set beforehand, so ADC adds 1)
- routines/Score/GetDrawInfo: replaced "sep #$20 : clc : adc #$0C" with "sep #$21 : adc #$0B" (set carry with SEP and ADC with -1)
- routines/SetPlayerClippingAlternate.asm: replaced "REP #$20 : CLC : ADC" with "REP #$21 : ADC" (clear carry with REP)
- routines/SetSpriteClippingAlternate.asm: replaced "REP #$20 : CLC : ADC" with "REP #$21 : ADC" (clear carry with REP)
- routines/Smoke/GenericDraw.asm: optimized OAM copy with 16 bit mode
- routines/SpinningCoin/GetDrawInfo.asm: fixed documentation

### CODE REVIEW

**Comment by Atari2** [comment]
Most of these changes seem relatively harmless and simple but I'm gonna ask anyway, have they been tested?

**Comment by kkevinm** [comment]
I haven't tested them but I can do it in the next days.

**Comment by Atari2** [comment]
Sounds good to me, just leave a comment here when these are tested and I'll merge

**Comment by Atari2** [comment]
I manually audited every single change and they look to be logically correct and should cause no behavior change.
I'm a bit confused at the `routines/Bounce/GenericDraw.asm` "optimization" change since according to !ar cycle both the versions take the same amount of cycles (16), but it doesn't hurt so I won't change it.

**Comment by kkevinm** [comment]
Oh sorry I couldn't get around to testing them.

> I'm a bit confused at the `routines/Bounce/GenericDraw.asm` "optimization" change since according to !ar cycle both the versions take the same amount of cycles (16), but it doesn't hurt so I won't change it.

Guess I did that because it's 1 byte less.

**Pull request merged**
