### PR TITLE
Update sa1def.asm

### PR DESCRIPTION
**Pull request by Iwakoro**
Supported for "!170B" etc

### CODE REVIEW

**Comment by Atari2** [comment]
Please don't reopen PRs that I specifically closed with a reason with NO changes, thanks.
Refer to this comment for explanation <https://github.com/JackTheSpades/SpriteToolSuperDelux/pull/94#issuecomment-1793513215>

**Comment by Iwakoro** [comment]
The changes are in place. I just wrote the ones I forgot to write.
See line 248.

**Comment by Atari2** [comment]
What I'm saying is that this PR is identical to #94 which I already closed once before, with a comment explaining why, and this PR contains the same exact changes as that one, with no variations, as you can see from the screenshot below. 
image
Please read my comment on #94 which I linked above.

**Comment by Iwakoro** [comment]
I referred to JackTheSpades/SpriteToolSuperDelux/asm/sa1def.asm but it didn't say...
I thought I forgot to write it down. Sorry.

screenshot

**Pull request closed without merging**
